spring:
  application:
    name: ai-code-assistant-lww
server:
  servlet:
    context-path: /api
  port: 8123

# springdoc-openapi????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xidian.aicodeassistantlww.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn